services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DBP}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBU}
      MYSQL_PASSWORD: ${DBP}
    ports:
      - "3306:3306"
    networks:
      - pb-games
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DBP}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # scylla:
    #   image: scylladb/scylla:latest
    #   container_name: scylla
    #   restart: always
    #   ports:
    #     - "9042:9042"
    #   volumes:
    #     - /mnt/temp:/var/lib/scylla
    #   networks:
    #     - scylla-network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:10000/metrics || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

    # queueb:
    #     image: maxwellmichael/paradisbend:QB-Latest
    #     container_name: queueb
    #     restart: always
    #     ports:
    #         - "3014:3014"
    #     networks:
    #         - scylla-network
    #     environment:
    #         - SCYLLA_HOST=scylla
    #     depends_on:
    #         - scylla
    # scylla:
    #     condition: service_healthy

# volumes:
#     scylla_data1:

networks:
  pb-games:
